version: '3.8'

services:
  a5:
    build:
      context: .
    image: mfe/a2:humble
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ../ros2_ws:/workspace
    working_dir: /workspace
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        colcon build --symlink-install &&
        source install/setup.bash &&
        ros2 launch a5_grader neil.launch.py &
        sleep 3 &&
        ros2 run a5_new_member hello_publisher --ros-args -r __ns:=/student &
        ros2 launch a5_new_member lpf.launch.py github_user:=student
      "
